class Constants:
    RANDOM_SEED = 67
    BATCH_SIZE = 125
    NUM_OF_LSTM_LAYERS = 1
    EMBEDDING_DIM = 32
    LSTM_HIDDEN_DIM = 32
    USE_BIDIRECTIONAL = False
    USE_ATTENTION_MECHANISM = False
    TOTAL_EPOCH_COUNT = 100
    ORIGINAL_DATA_DIMENSION = 4
    L2_LAMBDA_COEFFICENT = 0.0
    INITIAL_LR = 0.001
    DROPOUT_KEEP_PROB = 1.0
