class Constants:
    RANDOM_SEED = 67
    BATCH_SIZE = 8
    NUM_OF_LSTM_LAYERS = 2
    EMBEDDING_DIM = 64
    LSTM_HIDDEN_DIM = 64
    USE_BIDIRECTIONAL = True
    USE_ATTENTION_MECHANISM = False
    TOTAL_EPOCH_COUNT = 1000
    ORIGINAL_DATA_DIMENSION = 4
    L2_LAMBDA_COEFFICENT = 0.0
    INITIAL_LR = 0.001
    DROPOUT_KEEP_PROB = 1.0
