class Constants:
    def __init__(self):
        pass

    IMG_WIDTHS = [320, 480, 640]
    POSITIVE_IOU_THRESHOLD = 0.7
    NEGATIVE_IOU_THRESHOLD = 0.4
    MAX_INCLUSIVENESS_BB = 0.99
    IMAGE_COUNT_PER_BATCH = 3
    ROI_SAMPLE_COUNT_PER_IMAGE = 128
    POSITIVE_SAMPLE_RATIO_PER_IMAGE = 0.25

