class Constants:
    def __init__(self):
        pass

    # FAST RCNN - RoI Sampling Parameters
    IMG_WIDTHS = [320, 480, 640]
    POSITIVE_IOU_THRESHOLD = 0.7
    NEGATIVE_IOU_THRESHOLD = 0.4
    MAX_INCLUSIVENESS_BB = 0.99
    POSITIVE_PROPOSAL_SAMPLING_STD = 20.0
    IMAGE_COUNT_PER_BATCH = 3
    ROI_SAMPLE_COUNT_PER_IMAGE = 128
    POSITIVE_SAMPLE_RATIO_PER_IMAGE = 0.25
    POOLED_WIDTH = 7
    POOLED_HEIGHT = 7

    # ResNet Parameters
    NUM_OF_RESIDUAL_UNITS = 2
    NUM_OF_FEATURES_PER_BLOCK = [16, 32, 64, 128]
    FIRST_CONV_FILTER_SIZE = 3
    RELU_LEAKINESS = 0.1
    FILTER_STRIDES = [1, 2, 2]
    ACTIVATE_BEFORE_RESIDUALS = [True, True, False]
    BATCH_NORM_DECAY = 0.9
